title: Software Development and Open Source Blog
url: "https://mmuzaf.github.io"
baseurl: "/"
author:
  name: Maxim Muzafarov
  email: mmuzaf@apache.org

# To use the latest Minima version on GitHub Pages.
# remote_theme: jekyll/minima
# minima:
#   skin: auto

theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links

# To link only specific pages in your header, use this and add the path to the pages.
header_pages:
  - about.md

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Personal blog of Maxim Muzafarov. I write about software development, open source, and other topics that interest me, 
  learning and sharing knowledge with others.

relative_links:
  enabled: true
  collections: true

collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title.html
    folder: blog/db

include:
  - blog/Database_Links_and_Key_Takeaways.md
  - index.md
